config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "welcome#index"


  namespace :admin do
    resources :conversations
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  include ActionView::RecordIdentifier
  after_update_commit lambda { broadcast_replace_to self, target: "admin__#{dom_id(self)}", partial: "admin/conversations/line" }
  after_destroy_commit lambda { broadcast_remove_to self, target: "admin__#{dom_id(self)}"}

  paginates_per 5
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
end

app/controllers/admin/conversations_controller.rb
class Admin::ConversationsController < Admin::BaseController
  helper :hot_glue
  include HotGlue::ControllerHelper

  
  
  before_action :load_conversation, only: [:show, :edit, :update, :destroy]
  after_action -> { flash.discard }, if: -> { request.format.symbol ==  :turbo_stream }
 
  def load_conversation
    @conversation = (Conversation.find(params[:id]))
  end
  

  def load_all_conversations(page = params[:page] || 1)
    @conversations = ( Conversation.page(page))
  end

  def index
    load_all_conversations
  end

  def new 
    @conversation = Conversation.new()
   
  end

  def create
    modified_params = modify_date_inputs_on_params(conversation_params.dup)


    @conversation = Conversation.create(modified_params)

    if @conversation.save
      flash[:notice] = "Successfully created #{@conversation.name}"


      @page = (Conversation.count() / Conversation.default_per_page)
      @page += 1 if (Conversation.count() % Conversation.default_per_page) > 0

      load_all_conversations(@page)
      render :create
    else
      flash[:alert] = "Oops, your conversation could not be created. #{@hawk_alarm}"
      render :create, status: :unprocessable_entity
    end
  end


  def edit
    render :edit
  end

  def update
    modified_params = modify_date_inputs_on_params(conversation_params)
      

    if @conversation.update(modified_params)
      
      flash[:notice] = (flash[:notice] || "") << "Saved #{@conversation.name}"
      flash[:alert] = @hawk_alarm if @hawk_alarm
      render :update
    else
      flash[:alert] = (flash[:alert] || "") << "Conversation could not be saved. #{@hawk_alarm}"
      render :update, status: :unprocessable_entity
    end
  end

  def destroy
    begin

      @conversation.destroy
    rescue StandardError => e
      flash[:alert] = "Conversation could not be deleted."
    end
    load_all_conversations
  end

  def conversation_params
    params.require(:conversation).permit( [:name] )
  end

  def namespace
    "admin/" 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @conversation = Conversation.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/_errors.erb
<\%= turbo_frame_tag "errors" do %>
  <\% if resource.errors.any? %>
    <div id="error_explanation">
      <\% resource.errors.full_messages.each do |message| %>
        <div class="alert alert-danger">
          <\%= message %>
        </div>
      <\% end %>
    </div>
  <\% end %>
<\% end %>

app/views/admin/conversations/_errors.erb
<%= turbo_frame_tag "errors" do %>
  <% if resource.errors.any? %>
    <div id="error_explanation">
      <% resource.errors.full_messages.each do |message| %>
        <div class="alert alert-danger">
          <%= message %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/admin/conversations/_form.erb
<div class="row">
  <div class='col-md-1' >  
    <span class='<%= "alert-danger" if conversation.errors.details.keys.include?(:name) %>'  style="display: inherit;"  >
        <%= f.text_field :name, value: conversation.name, autocomplete: 'off', size: 40, class: 'form-control', type: '' %>
       
      
      <label class='small form-text text-muted'>Name</label>
    </span>
    <br />
  </div>

  <div class="col-md-2">
    <%= link_to "Cancel", admin_conversations_path,  {class: "btn btn-secondary"} %>
    <%= f.submit "Save", class: "btn btn-primary pull-right" %>
  </div>
</div>

app/views/admin/conversations/_line.erb
<%= turbo_stream_from conversation  %>
<%= turbo_frame_tag "admin__#{ dom_id(conversation) }" do  %>
  <div class='row scaffold-row' data-id='<%= conversation.id %>' data-edit='false'>
    <%= render partial: 'admin/conversations/show', locals: { conversation: conversation } %>

  </div>
<% end %>

app/views/admin/conversations/_list.erb
<%= turbo_frame_tag "admin__conversations-list"   do %>
  <div class="container-fluid scaffold-list">
    
      <h4>
        CONVERSATIONS
      </h4>
    

    <%= render partial: "admin/conversations/new_button", locals: {} %><br />

    
      
        <div class="row scaffold-heading-row">
          <div class='col-md-1'>Name</div>
          

          

          <div class=' scaffold-col-heading scaffold-col-heading-buttons col-md-2' >

          </div>
        </div>
      

      <% if conversations.empty? %>
    <div>
        None
    </div>
      <% end %>
      <% conversations.each do |conversation| %>
        <%= render partial: 'admin/conversations/line', locals: {conversation: conversation}
            .merge(defined?(nested_for) ? {nested_for: nested_for} : {})
      
        %>
      <% end %>
    <% if conversations.respond_to?(:total_pages) %><%= paginate(conversations) %> <% end %>
  
  </div>
<% end %>

app/views/admin/conversations/_new_button.erb
<%= turbo_frame_tag "admin__conversation-new" do %>
  <div>
    <%= link_to "New CONVERSATION",  new_admin_conversation_path, disable_with: "Loading...", class: "new-conversation-button btn btn-primary pull-right  " %>
  </div>
<% end %>

app/views/admin/conversations/_new_form.erb
<%= turbo_frame_tag "admin__conversation-new" do %>
<h3>
  New CONVERSATION
  </h3>
  <%= form_with model:  conversation, url: admin_conversations_path, method: :post do  |f| %>
    <%=  render partial: "admin/conversations/form",
      locals: { conversation: conversation, f: f} %>
  <% end %>
<% end %>

app/views/admin/conversations/_show.erb
<div class='col-md-1'><%= conversation.name %></div>




<div class=" scaffold-line-buttons  col-md-2" >
  

  
    <%= form_with url: admin_conversation_path(conversation), html: {data: {'turbo-confirm': "Are you sure you want to delete #{ conversation.name }?"}, style: "display: inline-block;"}, method: :delete do |f| %>
      <%= f.submit "Delete".html_safe,  class: "delete-conversation-button btn btn-primary btn-sm" %>
    <% end %>
  

  
  <%= link_to "Edit <i class='fa fa-1x fa-list-alt'></i>".html_safe, edit_admin_conversation_path(conversation), disable_with: "Loading...", class: "edit-conversation-button btn btn-primary btn-sm" %>
  
</div>

app/views/admin/conversations/create.turbo_stream.erb
<% if @conversation.errors.none? %>
  <%= turbo_stream.replace "admin__conversations-list" do %>
    <% logger.debug("rendering with " + {conversations: @conversations, page: @page}.to_json) %>
  <%= render partial: "list", locals: {conversations: @conversations, page: @page} %>
  <% end %>
  <% end %>
  <%= turbo_stream.replace "admin__conversation__conversation-new" do %>
  <% if @conversation.errors.none? %>
  <%= render partial: "new_button", locals: {} %>
  <% else %>
  <%= render partial: "new_form", locals: {conversation: @conversation} %>
  <% end %>
  <% end %>
  <%= turbo_stream.replace "flash_notices" do %>
  <%= render partial: "layouts/flash_notices" %>
  <% if @conversation.errors.any? %>
  <%= render partial: "errors", locals: {resource: @conversation} %>
  <% end %>
<% end %>

app/views/admin/conversations/destroy.turbo_stream.erb
<%= turbo_stream.remove "admin__" + dom_id(@conversation) do %>
<% end %>

app/views/admin/conversations/edit.erb
<%= link_to "<i class='fa fa-arrow-circle-left  2x'></i> Back to list".html_safe, admin_conversations_path %>

<%= turbo_frame_tag "admin__#{dom_id(@conversation)}" do  %>

  <div class="cell editable" style="position: relative;">

    <% if @conversation.errors.any? %>
      <%= render(partial: "admin/errors", locals: {resource: @conversation }) %>
    <% end %>

    <h2>Editing <%= @conversation.name %></h2>
    <%= form_with model: @conversation, url: admin_conversation_path(@conversation) do |f| %>
    <%=  render partial: "form",  locals: {:conversation => @conversation, f: f} %>
    <% end %>

  </div>

<% end %>

app/views/admin/conversations/edit.turbo_stream.erb
<%= turbo_stream.replace "admin__#{dom_id(conversation)}" do %>
  <%= render 'edit' %>
<% end %>

app/views/admin/conversations/index.erb
<div class="container-fluid">
  <div class="row"> <div class="col-md-12">
  

  <div class="clearfix"></div>
  <%= render partial: 'admin/conversations/list',
    locals: {conversations: @conversations, page: @page } %>

  </div></div>
</div>

app/views/admin/conversations/new.erb
<%= render partial: "new_form", locals: {conversation: @conversation} %>

app/views/admin/conversations/update.turbo_stream.erb
<%= turbo_stream.replace "conversation__#{@conversation.id}" do %>
  <%= render partial: 'line', locals: {conversation: @conversation } %>
<% end %>

<%= turbo_stream.replace "flash_notices" do %>
  <%= render partial: "layouts/flash_notices" %>
  <% if @conversation.errors.any? %>
  <%= render partial: "errors", locals: {resource: @conversation} %>
  <% end %>
<% end %>

app/views/layouts/_flash_notices.erb
<%= turbo_frame_tag "flash_notices" do %>
  <% unless notice.nil? %>
    <div class="alert alert-notice alert-dismissible">
      <%= notice %>
    </div>
  <% end %>
  <% unless alert.nil? %>
    <div class="alert alert-danger alert-dismissible">
      <%= alert %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TR7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <%= render partial: 'layouts/flash_notices' %>
  
    <%= yield %>
  </body>
</html>

app/views/welcome/_conversation.erb
<%= turbo_frame_tag "welcome__conversation__#{dom_id(conversation)}" do  %>
  <h1><%= conversation.name %></h1>
<% end %>

app/views/welcome/conversation.turbo_stream.erb
<% byebug  %>
<%= turbo_stream.replace "#{dom_id(@conversation)}" do %>
  <%= Time.current %>
  <%= render partial: "conversation", locals: {conversation: @conversation} %>
<% end %>

app/views/welcome/index.erb
<%= turbo_stream_from @conversation %>

<%= render partial: "conversation", locals: {conversation: @conversation} %>